export const paths = {
  root: '/',
  user: {
    root: `/users`,
    new: `/users/new`,
    edit: (id: string) => `/users/edit?id=${id}`,
    view: (id: string) => `/users/view?id=${id}`,
  },
  disease: {
    root: `/diseases`,
    new: `/diseases/new`,
    edit: (id: string) => `/diseases/edit?id=${id}`,
  },
  patient: {
    root: `/patients`,
    new: `/patients/new`,
    edit: (id: string) => `/patients/edit?id=${id}`,
    view: (id: string) => `/patients/view?id=${id}`,
    add_payment: (id: string) => `/patients/add-payment?id=${id}`,
    payment_history: (id: string) => `/patients/payment-history?id=${id}`,
    attendance_history: (id: string) => `/patients/attendance-history?id=${id}`,
  },
  attendance: '/attendance',
  payment_history: '/payment-history',
  notification: '/notifications',
  profile: '/profile',
  profile_edit: (id: string) => `/profile/edit?id=${id}`,
  comingSoon: '/coming-soon',
  maintenance: '/maintenance',
  page403: '/error/403',
  page404: '/error/404',
  page500: '/error/500',
  contact: '/contact',
  about: '/about',
  faqs: '/faqs',
  auth: {
    signIn: `/sign-in`,
    verify_otp: (email: string) => `/verify-otp?email=${email}`,
    signUp: `/sign-up`,
    forgotPassword: `/forgot-password`,
  },
};
